version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: read_quran_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: read_quran_db
    ports:
      - '5432:5432'
    volumes:
      - read_quran_db_data:/var/lib/postgresql/data
      - ./db/dump.sql:/docker-entrypoint-initdb.d/backup.sql
    restart: unless-stopped

volumes:
  read_quran_db_data:
